import 'package:flutter/material.dart';

class LegalSection {
  const LegalSection({required this.heading, required this.paragraphs});

  final String heading;
  final List<String> paragraphs;
}

/// Static legal copy shipped with the app. Mochi is fully on-device, so these
/// documents describe local storage and offline behaviour rather than a hosted
/// service. Keep the "last updated" date in sync when the text changes.
enum LegalDocument {
  privacyPolicy(
    title: 'Privacy Policy',
    icon: Icons.lock_outline_rounded,
    lastUpdated: 'September 2026',
    summary:
        'Mochi runs entirely on your phone. There is no account, no server, '
        'and no analytics. Your conversations, moods, memories, and profile '
        'stay in a local database on this device.',
    sections: <LegalSection>[
      LegalSection(
        heading: 'What stays on your device',
        paragraphs: <String>[
          'Your profile (name, and any optional bio or birthday), chats, mood '
              'check-ins, memories, pet state, food and satiety, mini-game '
              'scores, and settings are stored in a private SQLite database '
              'inside the app\'s storage on your phone. We never receive a copy.',
        ],
      ),
      LegalSection(
        heading: 'What we collect',
        paragraphs: <String>[
          'Nothing. Mochi has no telemetry, tracking, advertising, or '
              'crash-reporting services. It does not create an account and does '
              'not ask for your email, phone number, or any other personal '
              'identifier.',
        ],
      ),
      LegalSection(
        heading: 'When the app uses the internet',
        paragraphs: <String>[
          'Mochi needs the internet only to download the AI model file from '
              'Hugging Face on first launch or when you choose a different '
              'model. That download is handled by Hugging Face and is subject '
              'to their own privacy policy and terms.',
          'Once the model is stored on your device, Mochi works fully offline. '
              'Interrupted downloads resume from where they stopped.',
        ],
      ),
      LegalSection(
        heading: 'Device permissions',
        paragraphs: <String>[
          'Microphone is used for optional voice input. Photo and media access '
              'is used for optional image attachments. Notifications are used '
              'for optional milestone nudges. Battery optimisation and '
              'floating-window access are used only to keep the optional '
              'background Mochi bubble alive.',
          'Every permission is optional and is used on-device only. You can '
              'review or revoke them at any time in Android settings.',
        ],
      ),
      LegalSection(
        heading: 'Third-party model and libraries',
        paragraphs: <String>[
          'Mochi\'s replies are generated by the LFM2.5 language model created '
              'by Liquid AI. That model has its own licence terms, separate '
              'from this app. Open-source packages bundled into Mochi are '
              'listed under Open-source Licenses together with their licences.',
        ],
      ),
      LegalSection(
        heading: 'Children\'s privacy',
        paragraphs: <String>[
          'Mochi is a general-audience companion app and is not directed to '
              'children under 13. Because no personal data is collected or '
              'transmitted, there is no separate children\'s data to handle.',
        ],
      ),
      LegalSection(
        heading: 'Your choices and data removal',
        paragraphs: <String>[
          'You are in control. Uninstalling Mochi or clearing its app data '
              'permanently deletes your local database and any downloaded '
              'model files. There is no cloud copy to request or delete.',
        ],
      ),
      LegalSection(
        heading: 'Changes to this policy',
        paragraphs: <String>[
          'If this policy changes, the updated version ships with a new release '
              'and the date above is updated.',
        ],
      ),
    ],
  ),
  termsAndConditions(
    title: 'Terms and Conditions',
    icon: Icons.gavel_rounded,
    lastUpdated: 'September 2026',
    summary:
        'By installing or using Mochi you agree to these terms. Mochi is a '
        'local, pre-release companion app provided as-is.',
    sections: <LegalSection>[
      LegalSection(
        heading: 'Acceptance',
        paragraphs: <String>[
          'By downloading, installing, or using Mochi you agree to be bound by '
              'these terms. If you do not agree, do not use the app.',
        ],
      ),
      LegalSection(
        heading: 'Licence to use',
        paragraphs: <String>[
          'Mochi is licensed, not sold. Subject to these terms and the '
              'project\'s open-source licence, you may install and use the app '
              'on devices you own or control for personal, non-commercial use.',
        ],
      ),
      LegalSection(
        heading: 'On-device AI and no professional advice',
        paragraphs: <String>[
          'Replies are generated by a small language model running on your '
              'device. They may be inaccurate, incomplete, repetitive, or '
              'unexpected. Mochi is not a substitute for professional medical, '
              'legal, financial, or emergency advice, and it cannot contact '
              'emergency services. Do not rely on it for decisions with real '
              'consequences.',
        ],
      ),
      LegalSection(
        heading: 'Acceptable use',
        paragraphs: <String>[
          'Do not use Mochi to break the law, to harm or harass others, to '
              'produce illegal content, to tamper with device security, or to '
              'redistribute the bundled model in breach of its licence.',
        ],
      ),
      LegalSection(
        heading: 'Intellectual property',
        paragraphs: <String>[
          'The Mochi app source is released under the MIT licence. The LFM2.5 '
              'model is owned by Liquid AI and governed by its own licence. '
              'Mochi\'s name, artwork, and characters belong to the project. '
              'Nothing in these terms grants rights to the model beyond its '
              'licence.',
        ],
      ),
      LegalSection(
        heading: 'Availability and changes',
        paragraphs: <String>[
          'Mochi is pre-release software. Features may change, break, or be '
              'removed. Model downloads depend on third-party services that may '
              'be unavailable at any time.',
        ],
      ),
      LegalSection(
        heading: 'Disclaimer of warranties',
        paragraphs: <String>[
          'Mochi is provided "as is" and "as available", without warranties of '
              'any kind, whether express or implied, including fitness for a '
              'particular purpose and non-infringement.',
        ],
      ),
      LegalSection(
        heading: 'Limitation of liability',
        paragraphs: <String>[
          'To the maximum extent permitted by law, the project maintainer is '
              'not liable for any indirect, incidental, or consequential '
              'damages arising from your use of, or inability to use, Mochi.',
        ],
      ),
      LegalSection(
        heading: 'Changes to these terms',
        paragraphs: <String>[
          'These terms may be updated with a new release. Continued use of the '
              'app after an update means you accept the revised terms.',
        ],
      ),
    ],
  ),
  aiAndModelNotice(
    title: 'AI & Model Notice',
    icon: Icons.psychology_alt_rounded,
    lastUpdated: 'September 2026',
    summary:
        'Mochi thinks on your phone. This notice explains what that means for '
        'the replies you see and the model behind them.',
    sections: <LegalSection>[
      LegalSection(
        heading: 'A small model on your device',
        paragraphs: <String>[
          'Mochi\'s personality is produced by a quantized LFM2.5 model '
              '(1.2B by default, 2.6B optional) running through llama.cpp '
              'inside the app. Nothing is sent to a cloud AI service.',
        ],
      ),
      LegalSection(
        heading: 'Generated, not authored',
        paragraphs: <String>[
          'Every reply is generated on the fly and can be wrong, biased, or '
              'strange. Mochi does not browse the web, and it only "remembers" '
              'what is stored as a memory or present in the current chat. Treat '
              'replies as playful companionship, not as facts.',
        ],
      ),
      LegalSection(
        heading: 'Model licence',
        paragraphs: <String>[
          'The LFM2.5 model is provided by Liquid AI under its own licence. By '
              'downloading the model you also agree to that licence. The model '
              'files are not part of Mochi\'s MIT-licensed source.',
        ],
      ),
      LegalSection(
        heading: 'Open-source software',
        paragraphs: <String>[
          'Mochi is built on Flutter, llama.cpp, SQLite, and other open-source '
              'packages. Their licence texts are available from Settings → '
              'Open-source Licenses.',
        ],
      ),
      LegalSection(
        heading: 'Safety',
        paragraphs: <String>[
          'Mochi is not a safety service. If you are in danger or in crisis, '
              'contact local emergency services or a qualified professional.',
        ],
      ),
    ],
  );

  const LegalDocument({
    required this.title,
    required this.icon,
    required this.lastUpdated,
    required this.summary,
    required this.sections,
  });

  final String title;
  final IconData icon;
  final String lastUpdated;
  final String summary;
  final List<LegalSection> sections;
}
